### ISSUE TITLE
How to build cvxopt package with GLPK support

### ISSUE THREAD

**Issue by kmykman** [chaquo/chaquopy#1085]
I use cvoxpt in the public package repository. I need to use glpk in cvoxpt but I got error.

> ImportError("cannot import name 'glpk' from 'cvxopt'")

I saw from [this](https://ajfriendcvxpy.readthedocs.io/en/pow/install/index.html) in part "Install with GLPK support", it needs to install [GLPK](https://www.gnu.org/software/glpk/) and then install [CVXOPT](http://cvxopt.org/) with GLPK bindings.

```
CVXOPT_BUILD_GLPK=1
CVXOPT_GLPK_LIB_DIR=/path/to/glpk-X.X/lib
CVXOPT_GLPK_INC_DIR=/path/to/glpk-X.X/include
pip install cvxopt
```
Is that only can be achieved by building a new whl file? If so, how should the metadata yaml file be written?  I have tried
```
package:
  name: cvxopt
  version: "1.2.5"
requirements:
  host:
    -url: https://ftp.gnu.org/gnu/glpk/glpk-4.35.tar.gz
```
but seems like it is wrong.
