### ISSUE TITLE
OpenCV crashes on API level 15

### ISSUE THREAD

**Issue by mhsmith** [chaquo/chaquopy#45]
API level 16 and later work fine. Since less than 1% of [active devices](https://developer.android.com/about/dashboards/) are older than that, we're unlikely to look into this further.

Refs #31.

**Comment by mhsmith** [comment]
Log message from emulator: 

```
07-29 09:57:17.688 10091-10114/com.chaquo.python.pkgtest3 A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=128)
07-29 09:57:18.198 1129-1129/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'generic_x86/sdk_x86/generic_x86:4.0.4/MR1/3462039:eng/test-keys'
    pid: 10091, tid: 10114  >>> com.chaquo.python.pkgtest3 <<<
    signal 11 (SIGSEGV), code 128 (?), fault addr 00000000
     eax 00000000  ebx 972b89c0  ecx 98926388  edx 00000001
     esi 00000017  edi 98925c10
     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000 xss 0000007b
     eip 968333ce  ebp 942ecc8c  esp 942ecbd4  flags 00210296
07-29 09:57:18.268 1129-1129/? I/DEBUG:     #00  eip: 968333ce  /data/data/com.chaquo.python.pkgtest3/cache/chaquopy/AssetFinder/requirements-x86.zip/cv2/cv2.so
    stack: 
        #00  942ecbd4  0a282f28  [heap]
        #00  942ecbd8  942ecc5c  [stack:10114]
        #00  942ecbdc  942ecc64  [stack:10114]
        #00  942ecbe0  00000006  
        #00  942ecbe4  942ecc4c  [stack:10114]
        #00  942ecbe8  00000000  
        #00  942ecbec  00000000  
        #00  942ecbf0  00000000  
        #00  942ecbf4  00000000  
        #00  942ecbf8  41c00000  
        #00  942ecbfc  41c00000  
        #00  942ecc00  942ecc54  [stack:10114]
        #00  942ecc04  00000018  
        #00  942ecc08  00000018  
        #00  942ecc0c  0000001c  
        #00  942ecc10  00000039  
```
