### ISSUE TITLE
I encountered an issue while using the package build tool to build the third-party package geatpy.

### ISSUE THREAD

**Issue by GGBond333** [chaquo/chaquopy#994]
![error](https://github.com/chaquo/chaquopy/assets/95454371/71f73564-e7dc-4c94-baae-b20cee729158)
I encountered an issue while using the package build tool to build the third-party package geatpy.The error is as shown in the image, there are many .os C files in the source files of geatpy, and it says unknown library during the packaging process. I have also configured the C and C++ environment in the Linux environment. I don’t know how to resolve it. I hope you can help me, thank you.

**Comment by mhsmith** [comment]
Please create a fork of this repository, push your recipe for this package, and post the link here.

**Comment by mhsmith** [comment]
The normal approach to building a package that uses NumPy's API is to use a meta.yaml file like this:
```yaml
{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% elif PY_VER in ["3.9", "3.10", "3.11"] %}
    {% set numpy_version = "1.23.3" %}
{% elif PY_VER == "3.12" %}
    {% set numpy_version = "1.26.2" %}
{% endif %}

package:
  name: geatpy
  version: "2.7.0"

source:
  url: https://github.com/geatpy-dev/geatpy/archive/refs/tags/v2.7.0.tar.gz

requirements:
  build:
    - cython 0.29.36
  host:
    - numpy {{ numpy_version }}
    - python
```

And a patch like this in server/pypi/packages/geatpy/patches/chaquopy.patch:
```patch
--- src-original/setup.py       2022-01-09 08:07:10.000000000 +0000
+++ src/setup.py        2023-12-16 23:16:09.167474647 +0000
@@ -8,6 +8,10 @@
 #
 #    If you want to donate to it, please email geatpy@163.com
 
+# Chaquopy: prevent the compiled parts of NumPy from being imported.
+import builtins
+builtins.__NUMPY_SETUP__ = True
+
 import os
 import sys
 import shutil
```

But that fails with this error:
```
File "/home/smith/git/chaquo/chaquopy/server/pypi/packages/geatpy/build/2.7.0/cp38-cp38-android_21_arm64_v8a/env/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 82, in <module>
  File "<string>", line 63, in findAndCopy
FileNotFoundError: [Errno 2] No such file or directory: '_core/Linux/lib64/v3.8'
```

It looks like it's trying to copy some pre-built .so files. It's not easy for me to tell how you worked around this, because you've just copied the entire geatpy source code into your fork instead of creating a patch. But I can tell you that Linux .so files will not work on Android.
